on: push
name: GitHub Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.GITHUBSECRET }}
        SLACK_USERNAME: GitHub
        SLACK_TITLE: Push to sage
        SLACK_ICON: https://github.com/rtCamp.png?size=48
